Repository jfrog/build-info, pull requests merged in 2023-06, with the labels that each got.

#740 Fix getLatestBuildNumber wrong condition
  build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
Labels: bug

#741 Add new downloadHeader function to Artifactory manager
  build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
Labels: improvement

#739 Add timeout for exeCommand utility
  build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
Labels: improvement

#732 Support browser login requests
  build-info-client/src/main/java/org/jfrog/build/client/JFrogHttpClient.java
  build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClient.java
  build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClientBuilder.java
  build-info-client/src/test/java/org/jfrog/build/client/PreemptiveHttpClientBuilderTest.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/AccessManager.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/GetBrowserLoginRequestToken.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/SendBrowserLoginRequest.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/Utils.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/response/CreateAccessTokenResponse.java
  build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/AccessManagerTest.java
  build.gradle
Labels: new feature

#742 Remove XStream dependency
  build-info-api/src/main/java/org/jfrog/build/api/Agent.java
  build-info-api/src/main/java/org/jfrog/build/api/Artifact.java
  build-info-api/src/main/java/org/jfrog/build/api/Build.java
  build-info-api/src/main/java/org/jfrog/build/api/BuildAgent.java
  build-info-api/src/main/java/org/jfrog/build/api/BuildBean.java
  build-info-api/src/main/java/org/jfrog/build/api/BuildRetention.java
  build-info-api/src/main/java/org/jfrog/build/api/Dependency.java
  build-info-api/src/main/java/org/jfrog/build/api/MatrixParameter.java
  build-info-api/src/main/java/org/jfrog/build/api/Module.java
  build-info-api/src/main/java/org/jfrog/build/api/Vcs.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Agent.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Artifact.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildAgent.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildInfo.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildRetention.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Dependency.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Module.java
  build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Vcs.java
  build.gradle
Labels: improvement

#744 Fix Javadoc generation
  build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
Labels: ignore for release
