Repository jfrog/build-info, pull requests merged in 2023-09, with the labels that each got.

#754 Update dependencies
  build.gradle
Labels: improvement

#757 Improve handling of spaces in command execution utility on Windows
  build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
  build-info-extractor/src/testFixtures/java/org/jfrog/build/IntegrationTestsBase.java
Labels: bug

#758 Improve release checks
  release/pipelines.release.yml
Labels: ignore for release

#762 Upgrade commons-compress to 1.24
  build.gradle
Labels: improvement
